sudo: false
language: python
python:
  - "2.7"
install:
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable bikeshed
  - bikeshed update
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "7955d0063fe8"
  - COMMIT_AUTHOR_EMAIL: "jaffathecake@gmail.com"
